### ISSUE TITLE
Update to newer Azure Storage version

### ISSUE THREAD

**Issue by itpropro** [thdotnet/hexo-deployer-azure-blob-storage#3]
Please upgrade the version to a much newer version that also supports $web and $logs container names to support Azure Static Websites.
Just update to the current Version (2.10.2).

https://github.com/thdotnet/hexo-deployer-azure-blob-storage/blob/7db4af388a240647c40b27bc1e83a6ed0a44e349/package.json#L21

**Comment by itpropro** [comment]
Any updates on this? I don't really want to fork, that just leads to unnecessary fragementation.

**Comment by thdotnet** [comment]
Sorry for the delay, will solve today

**Comment by itpropro** [comment]
Thank you very much, I really appreciate your effort 👍

**Comment by thdotnet** [comment]
check now please

**Comment by itpropro** [comment]
It seems to work now, also fixed a few vulnerabilities in old npm dependencies.

**Comment by thdotnet** [comment]
Thanks for the help and sorry for the delay

**Comment by itpropro** [comment]
Can you please also publish the package to npmjs? Thank you :)

**Comment by danieljsummers** [comment]
I'll second this request - npmjs.com is still showing 1.0.5.

Thanks for your work on this; it'll be exactly what I was looking for, once I can send the files to the `$web` container. :)

**Comment by thdotnet** [comment]
Hi,

I was trying to update it on npm, don’t know why it’s still displaying the
old version. I will look on this later today.

Cheers
