### ISSUE TITLE
Storing azure keys in _config.yml?

### ISSUE THREAD

**Issue by JonathanMaccollum** [thdotnet/hexo-deployer-azure-blob-storage#6]
I keep the _config.yml for my site in git source control.  Is there a way to run this deploy task without placing the azure access keys in the _config.yml file? I'm a bit worried I'll accidentally save this and check it into source control for the world to see XD. Is there a better practice I should be following in this regard?

**Comment by thdotnet** [comment]
That's a good question. I'm not sure, I would need to take a look about how people solve this on node apps (I'm not a node developer)

**Comment by thdotnet** [comment]
a "workaround" is to rotate your azure storage keys after every deployment, this way if you commit the _config by accident there won't be a problem.

**Comment by JonathanMaccollum** [comment]
Thank you for the reply! That is a good practice in general it seems, thank you for the suggestion.

I also did find that per the documentation hexo allows one to specify multiple config files to combine together (for example a _config.prod.yaml that includes the deployment keys, added to the .gitignore file for example), however attempting to do this produces the error "Config file _config.yml _config.prod.yml not found, using default." That's a separate issue for hexo though.

Thanks again!
